// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBBOsQ-8qQwOFOYAyhUt_fDE0e6mEHXZQ',
    appId: '1:1026993281706:android:a0cf9af8a2988000424ed3',
    messagingSenderId: '1026993281706',
    projectId: 'churchserviceplanner-b467f',
    storageBucket: 'churchserviceplanner-b467f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcjzyhl8-tc98p9z9bn9bbc1vu6_1R9Ag',
    appId: '1:1026993281706:ios:09662c353f98c703424ed3',
    messagingSenderId: '1026993281706',
    projectId: 'churchserviceplanner-b467f',
    storageBucket: 'churchserviceplanner-b467f.appspot.com',
    iosBundleId: 'com.example.churchServicePlanner',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmE01SHBkAVohuqMIIhxQRw7HVMkgdDg0',
    appId: '1:1026993281706:web:3d592ee425f9201a424ed3',
    messagingSenderId: '1026993281706',
    projectId: 'churchserviceplanner-b467f',
    authDomain: 'churchserviceplanner-b467f.firebaseapp.com',
    storageBucket: 'churchserviceplanner-b467f.appspot.com',
  );
}
